### ISSUE TITLE
Some cleanup required for adding to Addin Registry

### ISSUE THREAD

**Issue by RickStrahl** [supershowwei/ImgurUploader-MarkdownMonster-Addin#1]
Hi, thank you for creating this Markdown Monster addin. It looks super useful.

In order to be added to the Addin registry however, it would be nice if you could clean things up a little bit. I haven't looked at code, but just looking at the screenshots there are a few things I think that should probably be addressed:

* Provide a configuration file and add configuration option to the menu
(you can take a look at other addins and see how they do that like the [Azure Blob Storage Addin](http://localhost/weblog/posts/2017/Apr/29/Creating-a-Markdown-Monster-Addin-Save-Images-to-Azure-Blob-Storage). Specifically they key should go into configuration and be encrypted in some way so it's not out in the open.

* The dialog needs a title
* Dialog can probably be a bit bigger and lay out a little nicer
* We also need a bigger icon (128x128 preferably)

I can help with this if necessary, but you might want to take a look for yourself first.

Again, thanks and I look forward to moving this into the registry. It'll be a great addition - I know people have asked for Imgur integration a few times.

**Comment by supershowwei** [comment]
I updated dialog tile, bigger icon, and nicer layout.

I still do not provide configuration window. Because, it easy to use and almost do not need configurations for uploading images to imgur.

I already create a pr MarkdownMonsterAddinsRegistry repository. Please review and give me a comment in your own time.

Thanks your comments.

**Comment by RickStrahl** [comment]
You don't need a configuration window - MM itself doesn't do that either, I just show the config file for configuration changes.

I'll take a look later today.

Thanks.

**Comment by supershowwei** [comment]
I got it. I readded configuration menuitem.

![](https://i.imgur.com/ZUV1Hhg.gif)

**Comment by RickStrahl** [comment]
Great! That looks much nicer!

 One more thing (still haven't time to look at the code): Wouldn't you want to store the client id in the configuration so that doesn't have to be put in each time? Either prefill it (if you think it has to be entered often. Does it?) or maybe another button on the toolbar to easily get to the configuration.

**Comment by supershowwei** [comment]
Of course, the client id will be saved now and it will be restored automatically on addin opened.

![image](https://user-images.githubusercontent.com/4360325/34827534-7c21094a-f715-11e7-8859-803017693ba5.png)
